// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3XK0a21chBs8INkoRLrGEOGCp5iNuv_8',
    appId: '1:1086330927496:web:b467bd442bf26320c1e23d',
    messagingSenderId: '1086330927496',
    projectId: 'wasurenai-113be',
    authDomain: 'wasurenai-113be.firebaseapp.com',
    storageBucket: 'wasurenai-113be.firebasestorage.app',
    measurementId: 'G-CL6EK16G2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwVw-xQQjmH_AtSCYCtTWqWH3fvUw0pyk',
    appId: '1:1086330927496:android:7f1666dc52d686fbc1e23d',
    messagingSenderId: '1086330927496',
    projectId: 'wasurenai-113be',
    storageBucket: 'wasurenai-113be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbgVH5jydTeiDDa7Y7SLBwCBdEPo2Ez8s',
    appId: '1:1086330927496:ios:bf5f903d9fd36221c1e23d',
    messagingSenderId: '1086330927496',
    projectId: 'wasurenai-113be',
    storageBucket: 'wasurenai-113be.firebasestorage.app',
    iosBundleId: 'com.example.wasurenai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbgVH5jydTeiDDa7Y7SLBwCBdEPo2Ez8s',
    appId: '1:1086330927496:ios:bf5f903d9fd36221c1e23d',
    messagingSenderId: '1086330927496',
    projectId: 'wasurenai-113be',
    storageBucket: 'wasurenai-113be.firebasestorage.app',
    iosBundleId: 'com.example.wasurenai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3XK0a21chBs8INkoRLrGEOGCp5iNuv_8',
    appId: '1:1086330927496:web:7afae1f385f4e551c1e23d',
    messagingSenderId: '1086330927496',
    projectId: 'wasurenai-113be',
    authDomain: 'wasurenai-113be.firebaseapp.com',
    storageBucket: 'wasurenai-113be.firebasestorage.app',
    measurementId: 'G-HY378PDP9C',
  );
}
